In [74]:
import pandas as pd
path="D:\\new_coding\\datasets\\dream_challenge\\olfactory_data\\olfactory_data\\"
# load the data dataset
#filenamename="TASK1_training"
#filenamename="TASK1_test_set_Submission_form"
filenamename="TASK1_leaderboard_set_Submission_form"

try:
    #TASK1_leaderboard_set_Submission_form = pd.read_csv(f"{path}TASK1_training.csv")
    TASK1_leaderboard_set_Submission_form = pd.read_csv(f"{path}{filenamename}.csv")
    #TASK1_leaderboard_set_Submission_form = pd.read_csv(f"{path}TASK1_test_set_Submission_form.csv")
    #TASK1_leaderboard_set_Submission_form = pd.read_csv(f"{path}TASK1_leaderboard_set_Submission_form.csv")
    print(" dataset has {} samples with {} features each.".format(*TASK1_leaderboard_set_Submission_form.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 34 samples with 52 features each.

In [75]:
# load the data dataset
try:
    TASK1_Stimulus_definition = pd.read_csv(f"{path}TASK1_Stimulus_definition.csv")
    print(" dataset has {} samples with {} features each.".format(*TASK1_Stimulus_definition.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 302 samples with 5 features each.

In [76]:
# load the data dataset
try:
    CID = pd.read_csv(f"{path}CID.csv")
    print(" dataset has {} samples with {} features each.".format(*CID.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 211 samples with 3 features each.

In [77]:
try:
    Mordred_Descriptors = pd.read_csv(f"{path}Mordred_Descriptors.csv", encoding='latin-1')
    print(" dataset has {} samples with {} features each.".format(*Mordred_Descriptors.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 209 samples with 1828 features each.

In [78]:
try:
    OpenPOM_Dream_RATA = pd.read_csv(f"{path}OpenPOM_Dream_RATA.csv", encoding='latin-1')
    print(" dataset has {} samples with {} features each.".format(*OpenPOM_Dream_RATA.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 209 samples with 139 features each.

In [79]:
try:
    Morgan_fingerprints = pd.read_csv(f"{path}Morgan_fingerprints.csv", encoding='latin-1')
    print(" dataset has {} samples with {} features each.".format(*Morgan_fingerprints.shape))
except:
    print("Dataset could not be loaded. Is the dataset missing?")

 dataset has 209 samples with 2050 features each.

In [80]:
print(f'1. TASK1_leaderboard_set_Submission_form: {TASK1_leaderboard_set_Submission_form.shape}')
print(f'2. TASK1_Stimulus_definition: {TASK1_Stimulus_definition.shape}')
print(f'3. CID: {CID.shape}')
print(f'4. Mordred_Descriptors: {Mordred_Descriptors.shape}')
print(f'6. OpenPOM_Dream_RATA: {OpenPOM_Dream_RATA.shape}')
print(f'5. Morgan_fingerprints: {Morgan_fingerprints.shape}')

1. TASK1_leaderboard_set_Submission_form: (34, 52)
2. TASK1_Stimulus_definition: (302, 5)
3. CID: (211, 3)
4. Mordred_Descriptors: (209, 1828)
6. OpenPOM_Dream_RATA: (209, 139)
5. Morgan_fingerprints: (209, 2050)

In [81]:
# Put all the column sets into a list
column_sets = [
    set(TASK1_leaderboard_set_Submission_form.columns),
    set(TASK1_Stimulus_definition.columns),
]
# Find common columns across all datasets
common_columns = set.intersection(*column_sets)

print("Common columns:")
print(common_columns)

Common columns:
{'stimulus'}

In [82]:
# Perform the join on the common column 'stimulus'
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition = pd.merge(TASK1_leaderboard_set_Submission_form, TASK1_Stimulus_definition, on='stimulus', how='left')

print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.shape}')
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.head(3)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: (34, 56)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,Sharp,Chlorine,Alcoholic,Plastic,Ozone,Metallic,molecule,dilution,solvent,Intensity_label
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,62444,0.00100,PG,H
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,61641,0.00001,PG,L
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11747,0.10000,PG,H

In [83]:
# Put all the column sets into a list
column_sets = [
    set(TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.columns),
    set(CID.columns),
]
# Find common columns across all datasets
common_columns = set.intersection(*column_sets)

print("Common columns:")
print(common_columns)

Common columns:
{'molecule'}

In [84]:
# Perform the join on the common column 'molecule'
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID = pd.merge(TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition, 
                                                                               CID, 
                                                                               on='molecule', 
                                                                               how='left')


print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.shape}')
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.head()

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: (34, 56)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: (34, 58)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,Alcoholic,Plastic,Ozone,Metallic,molecule,dilution,solvent,Intensity_label,SMILES,is_solvent
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,62444,0.00100,PG,H,CCCC(=O)SC,FALSE
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,61641,0.00001,PG,L,COC(=O)CCSC,FALSE
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11747,0.10000,PG,H,CCC(=O)C(=O)C,FALSE
3,A468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7945,0.00010,PG,L,CCOC(=O)CC(C)C,FALSE
4,A521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6561,0.10000,PG,H,CC(C)C=O,FALSE

In [85]:
# Put all the column sets into a list
column_sets = [
    set(TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.columns),
    set(Mordred_Descriptors.columns),
]
# Find common columns across all datasets
common_columns = set.intersection(*column_sets)

print("Common columns:")
print(common_columns)

Common columns:
{'SMILES', 'molecule'}

In [86]:
# Perform the join on the common column 'molecule'
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors = pd.merge(
    TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID, 
    Mordred_Descriptors, 
    on='SMILES', 
    how='left')

print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors.shape}')
#import ace_tools as tools; tools.display_dataframe_to_user(name="Merged DataFrame", dataframe=merged_df)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors.head()

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: (34, 56)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: (34, 58)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: (34, 1885)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.486053,31.656710,118.045236,6.943837,50.0,5.0,24.0,23.0,3.861111,1.916667
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.623153,33.372552,134.040151,7.446675,76.0,6.0,28.0,27.0,4.111111,2.166667
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.890957,32.688753,100.052430,6.670162,46.0,6.0,26.0,26.0,4.472222,1.777778
3,A468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.002025,35.665804,130.099380,5.656495,102.0,7.0,34.0,33.0,4.972222,2.250000
4,A521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.834109,27.254130,72.057515,5.542886,18.0,2.0,16.0,14.0,3.361111,1.333333

In [87]:
# Put all the column sets into a list
column_sets = [
    set(TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors.columns),
    set(OpenPOM_Dream_RATA.columns),
]
# Find common columns across all datasets
common_columns = set.intersection(*column_sets)

print("Common columns:")
print(common_columns)

Common columns:
{'solvent', 'SMILES'}

In [88]:
# Perform the join on the common column 'stimulus'
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA = pd.merge(
    TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors, OpenPOM_Dream_RATA, on='SMILES', how='left')

print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA.shape}')
print()
#import ace_tools as tools; tools.display_dataframe_to_user(name="Merged DataFrame", dataframe=merged_df)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA.head(3)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: (34, 56)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: (34, 58)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: (34, 1885)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA: (34, 2023)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,tropical,vanilla,vegetable,vetiver,violet,warm,waxy,weedy,winey,woody
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.615261,0.024177,0.632649,0.008305,0.003444,0.083525,0.066478,0.084674,0.081419,0.014715
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.745067,0.096485,0.631945,0.011266,0.021820,0.081766,0.182966,0.168403,0.255442,0.065456
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.013075,0.111305,0.348984,0.019220,0.066794,0.114841,0.084942,0.042831,0.196079,0.007254

In [89]:
# Put all the column sets into a list
column_sets = [
    set(TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA.columns),
    set(Morgan_fingerprints.columns),
]
# Find common columns across all datasets
common_columns = set.intersection(*column_sets)

print("Common columns:")
print(common_columns)

Common columns:
{'SMILES'}

In [90]:
# Perform the join on the common column 'stimulus'
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints = pd.merge(
    TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA, Morgan_fingerprints, on='SMILES', how='left')

print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA.shape}')
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.shape}')
#import ace_tools as tools; tools.display_dataframe_to_user(name="Merged DataFrame", dataframe=merged_df)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.head(3)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition: (34, 56)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID: (34, 58)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors: (34, 1885)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA: (34, 2023)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: (34, 4072)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,Col_2038,Col_2039,Col_2040,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
categorical_columns = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['stimulus', 'solvent_x', 'Intensity_label', 'SMILES', 'is_solvent', 'Lipinski', 'GhoseFilter']

In [92]:
# Select categorical columns
categorical_cols = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.select_dtypes(include=['object', 'category']).columns

# Count unique values in each categorical column
unique_counts = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints[categorical_cols].nunique()

# Display the result
print(unique_counts)

stimulus           34
solvent_x           3
Intensity_label     2
SMILES             34
is_solvent          1
Lipinski            1
GhoseFilter         2
dtype: int64

In [93]:
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.shape}')
#TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.drop(['SMILES', 'Lipinski'], axis=1, inplace=True)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.drop(['Lipinski'], axis=1, inplace=True)
print()
print(f'TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: {TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.shape}')

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: (34, 4072)

TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints: (34, 4071)

In [94]:
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.head(3)

,stimulus,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,...,Col_2038,Col_2039,Col_2040,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047
0,A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.set_index('stimulus', inplace=True)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.head(3)

,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,Citrus,...,Col_2038,Col_2039,Col_2040,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047
stimulus,,,,,,,,,,,,,,,,,,,,,
A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [96]:
# Step 1: Identify categorical columns
categorical_cols = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints.select_dtypes(include=['object', 'category']).columns

# Step 2: Select three categorical columns
selected_cols = categorical_cols[:3]  # Adjust indices as needed

# Step 3: Count unique values in each selected categorical column
for col in selected_cols:
    unique_vals = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints[col].nunique()
    print(f"Column: {col} - Unique Values: {unique_vals}")

print()
for col in selected_cols:
    unique_vals = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints[col].unique()
    print(f"Column: {col} - Unique Values: {len(unique_vals)}")
    print(f"Values: {unique_vals}")
    print()

Column: solvent_x - Unique Values: 3
Column: Intensity_label - Unique Values: 2
Column: SMILES - Unique Values: 34

Column: solvent_x - Unique Values: 3
Values: ['PG' 'NT' 'DEP']

Column: Intensity_label - Unique Values: 2
Values: ['H' 'L']

Column: SMILES - Unique Values: 34
Values: ['CCCC(=O)SC' 'COC(=O)CCSC' 'CCC(=O)C(=O)C' 'CCOC(=O)CC(C)C' 'CC(C)C=O'
 'CC(C)CC1=NC=CN=C1OC' 'CCCCCC=O' 'CN1CCCC1' 'CC(C)CCO' 'CC(C)CCC(=O)C'
 'C1=COC(=C1)CS' 'C1=CC=NC=C1' 'C1=CC=C(C=C1)COC(=O)C2=CC=CC=C2\xa0\xa0'
 'C1=CC=C(C=C1)C=O' 'CCCCCN' 'CCC/C=C/C=O' 'CCC/C=C/CO' 'CC1=CN=C(C=N1)C'
 'C1=CC=C(C=C1)S' 'CC(C)CC=O' 'CCCCCCCCCC(=O)OCC' 'CC(C)CO'
 'CC(=O)C1=CC=CC=N1' 'CC(=C)OC(=O)C' 'CSCCC=O' 'CCOC(=O)C(C)C'
 'CC(C=O)C1=CC=CC=C1' 'CC(C)CCCC(C)CCO' 'C1=COC(=C1)CSSCC2=CC=CO2'
 'CCCCCCCCS' 'COC1=CC=CC=C1S' 'CCC/C=C/C(=O)O' 'C/C=C/C=C/C=O'
 'CC1=CC(=O)CC(C1)(C)C']

In [97]:
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['Intensity_label'][0:10]

stimulus
A298    H
A299    L
A442    H
A468    L
A521    H
A858    H
A867    H
A904    L
A996    H
B015    L
Name: Intensity_label, dtype: object

In [98]:
mapping = {'H': 1, 'L': 0}
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['Intensity_label'] = TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['Intensity_label'].map(mapping)
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['Intensity_label'][0:10]

stimulus
A298    1
A299    0
A442    1
A468    0
A521    1
A858    1
A867    1
A904    0
A996    1
B015    0
Name: Intensity_label, dtype: int64

In [99]:
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['solvent_x'][20:30]

stimulus
D699     PG
D819     PG
G294     PG
G576     NT
G595     PG
G953     PG
H009    DEP
H521     NT
H584    DEP
H767     NT
Name: solvent_x, dtype: object

In [100]:
TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints['GhoseFilter'][0:10]

stimulus
A298    False
A299    False
A442    False
A468    False
A521    False
A858     True
A867    False
A904    False
A996    False
B015    False
Name: GhoseFilter, dtype: object

In [101]:
categorical_cols=['solvent_x','GhoseFilter']
# Assuming 'df' is your DataFrame and 'categorical_cols' is a list of categorical column names
df_encoded = pd.get_dummies(
    TASK1_leaderboard_set_Submission_form_TASK1_Stimulus_definition_CID_Mordred_Descriptors_OpenPOM_Dream_RATA_Morgan_fingerprints, 
    columns=categorical_cols, 
    drop_first=True, 
    dtype=int)
df_encoded.shape

(34, 4071)

In [102]:
df_encoded.head(3)

,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,Citrus,...,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047,solvent_x_NT,solvent_x_PG,GhoseFilter_True
stimulus,,,,,,,,,,,,,,,,,,,,,
A298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
A299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
A442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0

In [103]:
from datetime import datetime
current_date_time=datetime.now().strftime("%d_%B_%Y")
print(current_date_time)

05_June_2025

In [104]:
df_encoded.to_csv(f'dataset_on_{current_date_time}_{filenamename}.csv', index=False)

In [105]:
df3=pd.read_csv(f'dataset_on_{current_date_time}_{filenamename}.csv')
df3.head(3)

,Green,Cucumber,Herbal,Mint,Woody,Pine,Floral,Powdery,Fruity,Citrus,...,Col_2041,Col_2042,Col_2043,Col_2044,Col_2045,Col_2046,Col_2047,solvent_x_NT,solvent_x_PG,GhoseFilter_True
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0